const DEFAULT_PORT = 8080;
const WEB_SOCKET_TOPIC = 'GAME_QUESTION';
const DB_NAME = 'sequenceMaker';
const PUBLISH_INTERVAL = 12 * 1000;

const COLL_QUESTIONS = 'questions';

export { DEFAULT_PORT, WEB_SOCKET_TOPIC, DB_NAME, COLL_QUESTIONS, PUBLISH_INTERVAL };
