const DEFAULT_PORT = 8080;
const WEB_SOCKET_TOPIC = 'GAME_QUESTION';
const DB_NAME = 'sequenceMaker';
const PUBLISH_INTERVAL = 20 * 1000;
const USER_VALID_TILL = 15 * 1000;
const EXCLUDE_LIST_MAX_LEN = 100;

const COLL_QUESTIONS = 'questions';
const COLL_QUES_PUBLISH_LOG = 'questionPublishLog';

export {
  DEFAULT_PORT,
  WEB_SOCKET_TOPIC,
  DB_NAME,
  COLL_QUESTIONS,
  COLL_QUES_PUBLISH_LOG,
  PUBLISH_INTERVAL,
  EXCLUDE_LIST_MAX_LEN,
  USER_VALID_TILL,
};
